# Generated by Django 4.0 on 2022-04-08 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField(null=True)),
                ('avatar_size', models.IntegerField(null=True)),
                ('modified_by', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=5)),
                ('employee_type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=6)),
                ('marital_status', models.CharField(max_length=10)),
                ('citizenship', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('city_state', models.CharField(max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=20)),
                ('research_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigiuhr.researchcentre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='authentication.user')),
            ],
        ),
    ]
