# Generated by Django 4.0 on 2022-03-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('time', models.TimeField(auto_now_add=True)),
                ('call_type', models.CharField(choices=[('Official', 'Official'), ('Personal', 'Personal')], default='Official', max_length=10)),
                ('receptionist', models.CharField(choices=[('Anna AGIO', 'Anna AGIO'), ('Bridgit SAMOR', 'Bridgit SAMOR'), ('Gloria WINGAWE', 'Gloria WINGAWE'), ('Madeleine DICKSON', 'Madeleine DICKSON')], default='Anna AGIO', max_length=20)),
                ('call_requested_by', models.CharField(max_length=20)),
                ('call_to_name', models.CharField(max_length=50)),
                ('call_to_org', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('comments', models.TextField(max_length=200)),
                ('created_by', models.CharField(choices=[('Anna AGIO', 'Anna AGIO'), ('Bridgit SAMOR', 'Bridgit SAMOR'), ('Gloria WINGAWE', 'Gloria WINGAWE'), ('Madeleine DICKSON', 'Madeleine DICKSON')], default='Anna AGIO', max_length=30)),
                ('updated_by', models.CharField(choices=[('Anna AGIO', 'Anna AGIO'), ('Bridgit SAMOR', 'Bridgit SAMOR'), ('Gloria WINGAWE', 'Gloria WINGAWE'), ('Madeleine DICKSON', 'Madeleine DICKSON')], default='Anna AGIO', max_length=30)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
