# Generated by Django 4.0 on 2022-03-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigiucall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callregister',
            old_name='updated_by',
            new_name='modified_by',
        ),
    ]
